from enum import Enum

class RoleEnum(str, Enum):
    ADMINISTRATEUR = "ADMINISTRATEUR"
    SUPERVISEUR_DE_PREPARATION = "SUPERVISEUR_DE_PREPARATION"
    AGENT_DE_PREPARATION = "AGENT_DE_PREPARATION"
    AGENT_ACCUEIL = "AGENT_ACCUEIL"
