"""initial_migration

Revision ID: 8c7e7ad1a714
Revises: 
Create Date: 2026-02-09 13:52:08.506783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7e7ad1a714'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prixHT', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('disponibilite', sa.Boolean(), nullable=True),
    sa.Column('menu_type', sa.Enum('BEST_OF', 'MAXI_BEST_OF', name='menutype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prixHT', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('disponibilite', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('BOISSON', 'PRODUIT_UNIQUE', name='producttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATEUR', 'SUPERVISEUR_DE_PREPARATION', 'AGENT_DE_PREPARATION', 'AGENT_ACCUEIL', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('menu_products',
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('chevalet', sa.Integer(), nullable=True),
    sa.Column('sur_place', sa.Boolean(), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS_PREPARATION', 'PREPAREE', 'LIVREE', name='orderstatus'), nullable=True),
    sa.Column('preparateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preparateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_menus',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    op.create_table('order_products',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('order_menus')
    op.drop_table('orders')
    op.drop_table('menu_products')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('menus')
    # ### end Alembic commands ###
